frontend:
  build: .
  command: python3 -u app.py
  ports:
    - "8080:8080"
  volumes:
    - .:/opt/projetos/dev/rosa_crud
  links:
    - db
db:
  image: mongo:latest
  container_name: mongo-crud
  ports:
    - "27017:27017"
  volumes:
    - .:/opt/projetos/dev/rosa_crud/data   
 nginx:
  mage: nginx:1.13-alpine
  container_name: nginx
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  depends_on:
    - frontend
